import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import React from 'react';
import Timer from '../components/Timer/Timer';
import styles from '../styles/Home.module.scss'
import p from '../utils/prefixImages';


const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Timer date={Date.now() + 5000}/>

      <main className={styles.main}>
        test basePath
        <img src={p("/images/test.png")} />     
         </main>
    </div>
  )
}

export default Home
